$schema: '../cache/schemas/tasks.json'

inheritedBy:
  toolchain: 'node'

fileGroups:
  sources:
    - '*.{ts,js}'
    - 'src/**/*.{ts,js}'
    - '!**/*.test.{ts,js}'
  tests:
    - 'tests/**/*.{ts,js}'
    - '**/*.test.{ts,js}'
    - '!node_modules/**'

implicitInputs:
  - 'package.json'
  - '/package.json'
  - '/pnpm-workspace.yaml'
  - '/pnpm-lock.yaml'
