$schema: '../cache/schemas/tasks.json'

inheritedBy:
  tag: xo

tasks:
  lint:
    options:
      runFromWorkspaceRoot: true
    command:
      - xo
      - --config
      - './xo.config.js'
      - '--cwd=${projectRoot}'
    inputs:
      # Source and test files
      - '@group(sources)'
      - '@group(tests)'
      # Other config files
      - '*.config.*'
      # Project configs, any format, any depth
      - '**/.eslintrc.*'
      # Root configs, any format
      - '/.eslintrc.*'
      - 'types/**/*'
      - 'tsconfig.json'
      - '/tsconfig.options.json'
      - '/*.config.*'

  fix-lint:
    options:
      runInCI: false
    extends: lint
    args: '--fix'
