# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v6
      - uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true
          auto-setup: true
        env:
          MOON_NODE_VERSION: ${{ matrix.node-version }}
      - uses: 'jamestalmage/cache-node-deps@v6'
      - name: 'Install Dependencies'
        run: 'pnpm install --frozen-lockfile'
        shell: bash
      - run: 'moon ci --summary detailed'
        env:
          MOON_NODE_VERSION: ${{ matrix.node-version }}
        shell: bash
      - name: 'Pretty Print Moon Results'
        uses: 'appthrust/moon-ci-retrospect@v2'
        if: success() || failure()
      - name: 'Comment build status'
        uses: 'moonrepo/run-report-action@v1'
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Coverage Report'
        run: 'cat ./coverage/coverage-details.md >> $GITHUB_STEP_SUMMARY'
